### ISSUE TITLE
Odd stench

### ISSUE THREAD

**Issue by LanHikariDS** [Gamergotten/Megalograph#1]
Whenever running this program, my computer starts smelling of cum. When closing the program, the smell dissipates, so it can't just be my computer.

**Comment by Gamergotten** [comment]
thanks for logging this issue, i will investigate whenever i next have the opportunity to do so 🔥🔥🔥

**Comment by Gamergotten** [comment]
i have been unable to replicate this issue unfortunately, so i think it surely must be something on your end
as of such, i will be closing this issue

please do not hesitate to contact me again if you have any further inquiries &or issues 😄
