### ISSUE TITLE
GlobalTimer definition issues

### ISSUE THREAD

**Issue by BOS304** [Gamergotten/Megalograph#2]
The console will report error when I add a new globaltimer and change the value.
The error definition.
>  
    <globaltimers>
    <globaltimers-child0 v="">
    <globaltimers-child0 v="">
    <NumericTypeRef>
    <NumericTypeRef v="Int16">
    <UnanmmedInt v="0" />
The decompiled one from race
> 
    <globaltimers>
    <globaltimers-child0>
    <NumericTypeRef>
    <NumericTypeRef v="Int16">
    <UnanmmedInt v="1" />

**Comment by Gamergotten** [comment]
interesting, i thought i got all those issues, but it seems otherwise
i'll take a peep tomorrow

**Comment by Gamergotten** [comment]
ok after looking at this, im surprised i didn't catch this issue
i updated the method of writing nodes but didn't update it completely (i probably got distracted while programming and forgot all about it)

issue should be fixed with next release

**Comment by Gamergotten** [comment]
lol, i hope that issue wasn't a major inconvenience whoever you are, but its now fixed (at least i think) so i can close this
